# For reference, I used this to figure out how to configure multiple services with docker compose:
# https://learn.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/multi-container-applications-docker-compose

services:
  scheduling:
    container_name: scheduling
    build:
      context: ./scheduling  # tells docker where the root directory of this service is, so it knows where to find this service's Dockerfile and how to build the docker image for this service
    ports:
      - 8000:5000
    depends_on:
      - rabbitmq

  image-management:
    container_name: image-management
    build:
      context: image-management/
    ports:
      - 8080:5000
    depends_on:
      - rabbitmq

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12-management
    ports:
      - 5672:5672   # this is the actual rabbitmq communication port
      - 15672:15672 # port for web interface for managing rabbitmq
