# For reference, I used this to figure out how to configure multiple services with docker compose:
# https://learn.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/multi-container-applications-docker-compose

services:
  relay-api:
    container_name: relay-api
    build:
      context: ./ # The build context for each service is the current folder and not the service's folder because the requirements.txt is in the current folder and needs to be copied by the Dockerfile into the container.
      dockerfile: ./event_relay_api/Dockerfile
    volumes:
      - ./app_config:/code/app_config
      - ./event_relay_api:/code/event_relay_api # This is a volume that allows the container to see the code changes made on the host machine.
    ports:
      - 80:5000
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgres

  satellite-activities:
    container_name: satellite-activities
    build:
      context: ./
      dockerfile: ./satellite_activities_service/Dockerfile
    volumes:
      - ./app_config:/code/app_config
      - ./satellite_activities_service:/code/satellite_activities_service
    ports:
      - 82:5000
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgres

  image-management:
    container_name: image-management
    build:
      context: ./ 
      dockerfile: ./image_management_service/Dockerfile
    volumes:
      - ./app_config:/code/app_config
      - ./image_management_service:/code/image_management_service
    ports:
      - 83:5000
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgres

  gs-outbound:
    container_name: gs-outbound
    build:
      context: ./
      dockerfile: ./ground_station_out_bound_service/Dockerfile
    volumes:
      - ./app_config:/code/app_config
      - ./ground_station_out_bound_service:/code/ground_station_out_bound_service
    ports:
      - 84:5000
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgres
    
  scheduler-worker:
    container_name: scheduler-worker
    build: 
      context: ./
      dockerfile: ./scheduler_service/Dockerfile
    command: celery -A config.celery_app worker --loglevel=${LOG_LEVEL}
    volumes:
      - ./app_config:/code/app_config
      - ./scheduler_service:/code/scheduler_service
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672   # this is the actual rabbitmq communication port
      - 15672:15672 # port for web interface for managing rabbitmq

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: soso_db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 85:80
    depends_on:
      - postgres

volumes:
  postgres:
  pgadmin:
