name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for opening your first issue. Kindly provide detailed information, and our team will promptly address it."
        pr-message: "Congratulations on your first pull request! Please adhere to our contribution guidelines. Our team will review and merge it. Thank you for your contribution."
